### ISSUE TITLE
🐛Having subtitles with special styles causes a grey box to cover screen

### ISSUE THREAD

**Issue by Billybobertjoe** [DonutWare/Fladder#447]
### Description

i was watching demon slayer, and some of the subtitles for it have a special style and effect added to them. it works fine in the jellyfin IOS app, but fladder seems to have issues with them. 

### Reproduction steps

```bash
1. play any media with styled subtitles.
2. turn on subtitles
3. screen gets covered by a grey and slightly transparent box whenever styled subtitles are shown
```

### Screenshots

<img width="2532" height="1170" alt="Image" src="https://github.com/user-attachments/assets/41a09276-8579-4ff2-b0ff-e34ab62d7c9b" />
<img width="2532" height="1170" alt="Image" src="https://github.com/user-attachments/assets/6457b15e-450c-4c00-99f4-f20f5ab1184d" />

<img width="2532" height="1170" alt="Image" src="https://github.com/user-attachments/assets/730e2290-fc99-45cc-861d-185d26bc2029" />

### Logs

```bash
[SEVERE  |  Flutter error: Invalid argument(s): 0.0, 2025-08-09T10:18:20.422432

#0      double.clamp (dart:core-patch/double.dart:232)
#1      SubtitleText.build.<anonymous closure> (package:fladder/models/settings/subtitle_settings_model.dart:212)
#2      _LayoutBuilderElement._rebuildWithConstraints.updateChildCallback (package:flutter/src/widgets/layout_builder.dart:233)
#3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3046)
#4      _LayoutBuilderElement._rebuildWithConstraints (package:flutter/src/widgets/layout_builder.dart:272)
#5      RenderAbstractLayoutBuilderMixin.layoutCallback (package:flutter/src/widgets/layout_builder.dart:335)
#6      RenderObjectWithLayoutCallbackMixin.runLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:4160)
#7      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2885)
#8      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1209)
#9      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2884)
#10     RenderObjectWithLayoutCallbackMixin.runLayoutCallback (package:flutter/src/rendering/object.dart:4160)
#11     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:449)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:2766)
#13     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:243)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:2766)
#15     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:62)
#16     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:646)
#17     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:673)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:2766)
#19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:2766)
#21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:2766)
#23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:2766)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:2766)
#27     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:62)
#28     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:646)
#29     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:673)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:2766)
#31     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:62)
#32     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:1202)
#33     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:1255)
#34     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2614)
#35     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1160)
#36     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1173)
#37     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:629)
#38     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1242)
#39     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:495)
#40     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1438)
#41     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1351)
#42     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1204)
#43     _invoke (dart:ui/hooks.dart:331)
#44     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:444)
#45     _drawFrame (dart:ui/hooks.dart:303)
]
```

### Platform

iOS

### App Version

v0.7.0 (232)

**Comment by Billybobertjoe** [comment]
the grey box blocks any input, and i have to tap on sliver of the screen that isnt covered to bring up the playback controls

**Comment by Billybobertjoe** [comment]
Enabling 'Native Libass Subtitles' fixes it and allows the subtitles to show with their custom styling

**Comment by PartyDonut** [comment]
Is this with any stylized(.ass) subtitles?

**Comment by Billybobertjoe** [comment]
Seems to be. I have to have "Native Libass subtitles" enabled for them to work properly. its so weird how the grey box also blocks input for any items behind it

**Comment by PartyDonut** [comment]
Thanks for the info will have a look.

**Comment by giulianob** [comment]
@PartyDonut this also happens with normal subtitles if you make the font size larger. I don't have libass subtitles enabled.

https://github.com/user-attachments/assets/e92c8f8d-3394-434d-aa6d-7e5c24520866

**Comment by HirschBerge** [comment]
> @PartyDonut this also happens with normal subtitles if you make the font size larger. I don't have libass subtitles enabled.

It definitely has something to do with screen realesate too. I haven't been able to get it to happen on a streaming device, but it's consistent on phones

**Comment by HirschBerge** [comment]
It seems with 0.10 that the option to use ASS has been removed entirely. This is obviously not the correct "solution" to this. Taking away the option is the wrong decision.

Please return this

Correction:

Ability to change the player to MPV is missing on TV which allows ASS to be used.

This makes most anime impossible to watch. Please fix asap

**Comment by PartyDonut** [comment]
> It seems with 0.10 that the option to use ASS has been removed entirely. This is obviously not the correct "solution" to this. Taking away the option is the wrong decision.
> 
> Please return this
> 
> Correction:
> 
> Ability to change the player to MPV is missing on TV which allows ASS to be used.
> 
> This makes most anime impossible to watch. Please fix asap

Calm down nothing was removed, it was a bug in the gradle build process. It's fixed in the current nightly builds.

The MPV player is a bit different from what Android TV would require and would require a complete re-work of the current logic. So for the foreseeable future Exoplayer will remain the default player for Android TV.

Now considering the issue itself

> [@PartyDonut](https://github.com/PartyDonut) this also happens with normal subtitles if you make the font size larger. I don't have libass subtitles enabled.
> screen-20251017-005403.2.mp4

The subtitle editor is a approximation of the subtitles that will be shown in the video player. Hence the grey screen here has no affect on the player itself. So it's a bug but a different one 😅.

Can someone check if this has been fixed, there was a bug that caused the subtitle renderer to still be active even with ass subtitles which was fixed in #777. Which could have caused this.

**Comment by HirschBerge** [comment]
>The MPV player is a bit different from what Android TV would require and would require a complete re-work of the current logic. So for the foreseeable future Exoplayer will remain the default player for Android TV.

Well it had the option before, and now does not. Soo....
Either way, Exoplayer in other clients, such as Wholphin displays subtitles correctly all the time regardless of format Was #777 included in 0.10.1? Timeline makes me think it should have been. That release has had no issues on mobile android, but TV android, at the risk of pissing you off again, just doesn't show ASS period.

**Comment by JeWe37** [comment]
#777 was not included in 0.10.1 but is included in the latest nightly build. I just tested it on that build and sadly I am still seeing the described behavior of no ASS subtitles showing at all, while e.g. SRT works fine. Do you have any samples that you believe should work @PartyDonut such that the issue can be narrowed down?
